replicaCount: 2

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: chamados.ntu.org.br
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: chamados-ntu-tls
      hosts:
        - chamados.ntu.org.br
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - chamados-nti
          topologyKey: kubernetes.io/hostname
