apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chamados-postgres-data
  namespace: chamados-nti
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
