apiVersion: v1
kind: Service
metadata:
  name: chamados-postgres
  namespace: chamados-nti

spec:
  type: ClusterIP

  selector:
    app: chamados-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
